### PR TITLE
Add copy edits to text

### PR DESCRIPTION
**Pull request by evale124**
Small copy edits to history page. No major changes. 

- Under 2017, the second sentence reads "discoverability, longevity, and **objectness** of digital catalogues." Is this the intended word?

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
That was a term we used to use a lot more. It's summarized well here: https://www.getty.edu/publications/osci-report/remaining-challenges/ under the section "reader confusion about catalogue boundaries". However, we stopped using it because it is not a clear concept. That said if we reduce that sentence down to just discoverability and longevity then it feels like we are missing something. What if we did: *particularly around the discoverability and the longevity of digital catalogues, both as objects in the world and as a sustainable publishing practice.* That's adapted from the History of Quire in the current documentation: https://gettypubs.github.io/quire/about/.  (I recognize it's still a bit awkward...)

**Comment by evale124** [comment]
I think the issue is with the use of object itself. The word comes across as a placeholder for something we want to say but can't quite describe (even though I know this is not the case) which could accidentally be misinterpreted by readers. Do we mean object in the sense of tangibility/concreteness, or as a goal, like objective?

**Comment by Erin-Cecele** [comment]
My understanding is that it means tangibility/concreteness. According to the OSCI report "readers reported that they sometimes had difficulty recognizing when they were "inside" the catalogue..."

**Comment by evale124** [comment]
I read the report section as well and I think I better understand the problem now. From my understanding, the issue is that of readers recognizing the publication as its own entity, as a singularity? I know there was confusion about the boundaries of the catalogue. Correct me if I'm wrong.

**Comment by Erin-Cecele** [comment]
Yes, I think we are on the same page with our understanding.

**Pull request merged**
