### PR TITLE
Edit half of documentation subheadings

### PR DESCRIPTION
**Pull request by evale124**
Issue #247 Still IN-PROGRESS

- Changed formatted words in certain areas, should I remove formatting across documentation pages for subheadings?
- on the For developers page make sure the Copyright&About and Working with Text links are functional.

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
@evale124 yes, rather than create a new issue let's add removing formatting from subheadings throughout the docs to this issue. thank you so much!

**Comment by evale124** [comment]
Addresses issue #247 

No major changes

- Wanted to make sure that  _Pages and Plain Text_ in first paragraph under Collection Catalogues page should remain unlinked?
- On Contributors page, "page types" link is broken. 
- On Style Customization page >>> Update Your Theme to a Newer Version subheading, "style variables" phrase (underlined, in blue) missing pop-up description.

**Comment by Erin-Cecele** [comment]
For bullet #1 - This should link to *Page Types & Structure* looks like the text is referencing outdated section names. 

For bullet #2 - I'll look into this but I think many of the links will be broken because URLS have changed due to the new structure of the website. So don't worry about broken links right now. 

For bullet #3 - I don't think style variables needs a pop-up definition. When you click on it it takes you to a specific section of the documentation. But good attention to detail!

**Comment by evale124** [comment]
Good to know!

**Pull request merged**
