### PR TITLE
Ed articles videos 314

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Addresses issue #314. 

How is this as a jumping-off point for the Articles & Videos section? 

Note, I added "How-To Guides" as an H2 because "Why Open Source" and "How it Works" felt weird being lumped together with the "Learning GitHub" and "Learning Command-line" instructions. 

Also curious what you think of the Command-line instructions. They're based on the script I wrote for the first video tutorial I want to record. Is it too redundant with the Quire Basics Tutorial?

### CODE REVIEW

**Comment by geealbers** [comment]
Yes, this is a good start. I like breaking out How-To Guides as their own thing, and in fact this brings up a couple questions for me.

First, isn't the Getting Started Tutorial just a long How-To? Could it be folded in there and then Articles & Videos becomes the lead page for this section? And I'd also make How-To the lead section of the page, above articles. Or, do you see expanding the Tutorials into more?

Second, should we consider organizing videos more by what they are, than by the fact that they're videos? I could envision them as text links with little video icon indicators that either went to youtube, or to their own page on our site with the video embedded in it (and maybe in the future, full transcripts in text below). And i think the OPF one is sort of article-ish, and the other two are sort of how to demos.

What do you think?

**Comment by Erin-Cecele** [comment]
While the Tutorial is basically a long "how-to," I worry it will get lost if it's buried in the Articles & Videos page (even if that becomes the lead page).  

In the long run, I've been considering replacing that all-in-one tutorial doc with individual tutorials (both text and video) guiding people through the various steps of Quire. For example, there would be an embedded video walking users through command line above and a link to the PDF with same instructions (but written out) below. In that case, I think those videos and PDFs would jointly become the Tutorials page. 

The Articles & Videos page would then become informative articles (like open source and how-to) and then webinars and presentations (which could be broken out separately and not just lumped together as videos).

Hope this makes sense. I'd be happy to discuss further on Monday.  For now, I will definitely move How-To's above the Articles section.

**Comment by geealbers** [comment]
I really like the idea of breaking down the main tutorial into it's constituent parts. It sort of feels that way when you look in the sidenav for that page.

Screen Shot 2020-10-22 at 3 21 14 PM

And yes, let's talk more about the organization of this section on Monday. I'm thinking about users coming to a set of pages to choose from that say "Tutorial", "Articles & Videos", and "Resources" and I wonder where we'd expect them to go and why they'd choose one over the other, etc.

**Comment by geealbers** [comment]
I like the commit you just pushed. The descriptive sentences are a nice touch

**Pull request merged**
