### PR TITLE
Copy edits to how quire works

### PR DESCRIPTION
**Pull request by evale124**
Addresses issue #230 

All links work, no major edits necessary. 

-I don't mind that it's hidden and doesn't have a tab, which I think would be excessive, but I do think it could be more accessible. I didn't realize where it was because I accidentally skimmed right over the graphic which links to it, so I think other people might also not see it. 

-What if Ruth's quote is placed before the subheading "Static Site Generation"? Where it occurs now sort of breaks the flow between the subheading and the text, or perhaps it is the placement of the video.

### CODE REVIEW

**Review by Erin-Cecele — APPROVED** [review]
Great edits @evale124!

**Comment by Erin-Cecele** [comment]
@evale124 I agree that "How It Works" might be a little hidden. Do you have suggestions for where else it might be linkable so it doesn't get completely lost?

**Comment by geealbers** [comment]
I actually had the same experience as @evale124 as I scrolled right by the link. In part I think because it doesn't function visually as a link as it does a heading and an image when it's just one thing and it's this size. (As opposed to when there are two or three of these image/heading blocks side by side like on the cover.) Maybe in addition to finding other places to link from, we also try using the image by itself and then adding a button with the call to action text? Does that make sense?

**Comment by evale124** [comment]
Oh I like Greg's idea, but would it go under the image or somewhere else on the page? Also, I thought about linking to other pages but I wasn't sure what other pages it would make sense belonging on except maybe the developers section.

**Comment by Erin-Cecele** [comment]
I think that's a good idea and actually what I ended up doing on the Join Us page. 
Screen Shot 2020-09-08 at 3 28 07 PM

I will create a new issue to test out using the image and an action button on "What Is Quire" page. If we like it then I will update the other pages that use that style.

Question @geealbers can you recommend how to tweak the CSS so we can get the action buttons in the center of the screen rather than off to the left?

**Pull request merged**
