### PR TITLE
Copy edits to homepage

### PR DESCRIPTION
**Pull request by evale124**
Addresses issue #220 

No major changes

-Updated broken links
- What if the subheading below the main heading was "Online, Print, E-book" without the conjunction/preposition?

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
@evale124 that thought crossed my mind as well. I this it would make things a pinch cleaner. Why don't you go ahead and make the change. Greg and I can revisit later.

**Comment by evale124** [comment]
There is no way to space them out as standalone on the same line right? Without the commas? 
Online    Print     E-book
Or would that look weird?

**Comment by Erin-Cecele** [comment]
I think it would look weird without separation. Another option could be using the vertical line | to seperate words but I wonder if that might be too noisy compared to commas.

**Comment by evale124** [comment]
Yeah I also thought of the little dot • but what do you think?
Online • Print • E-book

**Comment by Erin-Cecele** [comment]
Oh! Give that a try!!

**Comment by evale124** [comment]
The slider images only link to the images themselves, would it be possible to link the images directly to the websites? Like when I click on the image go directly to the project?

**Comment by Erin-Cecele** [comment]
There is a separate issue open to address this! #240 Though it only addresses User Showcase page. I will update issue to address homepage as well.

**Pull request merged**
