### PR TITLE
Edits to open source page

### PR DESCRIPTION
**Pull request by evale124**
Addresses issue #232 

No major changes made.

-What do you think of making the last full paragraph (i.e. "If Quire is unable to...") a footnote (like an asterisk or similar) instead of part of the main body? I like how the previous paragraph finalizes the page, but do correct me if there are issues with this suggestion.

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
Yes, I like that idea! It feels important to include but it is abrasive so any way to minimize it feels good to me.

**Review by Erin-Cecele — COMMENTED** [review]
How about "minimal" rather than "minor"? Otherwise, all good!

**Comment by geealbers** [comment]
@evale124 and @Erin-Cecele, I took a stab at reworking the last couple paragraphs. A little more than I'd planned to do, but I think I like how it's working. What do you both think?

**Review by Erin-Cecele — COMMENTED** [review]
This looks great. Thank you, Greg. I see you eliminated the text about what happens if Quire is not open-sourced in 2022. Are you thinking of moving this elsewhere or just keeping it off the site in general?

**Comment by geealbers** [comment]
Ultimately, I thought it most important to give potential users a sense of what they can do with Quire now, and then indicate that they'll continue to be able to do that even if we didn't make it formally open source. I just couldn't get the wording right to be more explicit about what would happen were we not to meet our 2022 goal without sounding like too much of a downer. AS @evale124 pointed out originally.

**Comment by Erin-Cecele** [comment]
OK. That's understandable. Let's keep off the site.

**Pull request merged**
