### PR TITLE
Website developer edit

### PR DESCRIPTION
**Pull request by Erin-Cecele**

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
@geealbers I accidentally requested for this branch to merge with the master. Is there a way to fix it so the merge request is for theme-update-v18 instead?

**Comment by geealbers** [comment]
Yep! There's an "Edit" button on the right side of the github PR page, across from the "Website developer edit #218" page title. You can change the branch you're merging into there.

**Comment by geealbers** [comment]
What was your idea in moving the Learn section to be below Documentation? Just curious

**Comment by Erin-Cecele** [comment]
If reading the headers from left to right, it seemed to make sense that you would review the documentation before proceeding on to the learn section. The main reason I placed learn before the documentation in the previous versions was because I felt it got lost in the side menu. This is still a concern, but I feel like the documentation should take precedence.

**Pull request merged**
